# .github/workflows/ci.yml

name: 🧪 Nix Flake CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-flake:
    name: ✅ Check Flake
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🧊 Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: 🔍 Run `nix flake check`
        run: nix flake check

      - name: 🚀 Test `nix run`
        run: nix run . -- --version || nix run .
